Added 'Add' and 'Use'  methods for Startup in ASP.net Core
mukmyash/QuartzHostedService pull request #2
Opened 2019-01-11 11:13 UTC by maikebing

- Added  Asp.Net Core Sample
- Added 'Add' and 'Use'  methods for Startup in ASP.net Core

2019-01-11 19:57 UTC, mukmyash requested changes

2019-01-11 19:57 UTC, mukmyash commented on .travis.yml
> +dotnet: 2.2
Travis can't build with this configuration.
For fix this issue, you must set 'xenial' value for property 'dist' (line 3)
 
more info: https://github.com/travis-ci/travis-ci/issues/9684#issuecomment-447683968

2019-01-11 20:03 UTC, mukmyash commented on .travis.yml
> +dotnet: 2.2
Sample travis configuration for build on .net core 2.2
https://github.com/mukmyash/QuartzHostedService/pull/4/files

2019-01-11 20:03 UTC, mukmyash commented on .travis.yml
> +dotnet: 2.2
Sample travis configuration for build on .net core 2.2
https://github.com/mukmyash/QuartzHostedService/pull/4/files

2019-01-12 00:13 UTC, maikebing commented on .travis.yml
> +dotnet: 2.2
Ok! is done.

2019-01-12 17:04 UTC, mukmyash approved these changes

2019-01-12 17:04 UTC, merged